# Generated by Django 5.1.2 on 2024-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_rename_dni_cliente_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='curp',
            field=models.CharField(max_length=225),
        ),
    ]
