# Generated by Django 5.1.2 on 2024-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='dni',
        ),
        migrations.AddField(
            model_name='empleado',
            name='curp',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
